# Generated by Django 4.2.16 on 2024-12-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
